### ISSUE TITLE
Is it possible to make generated images interactable?

### ISSUE THREAD

**Issue by NB574** [lucaorio/obsidian-image-gallery#5]
E.g. alt+right mouse click opens the source image within the file system? That would be great if it's possible.

**Comment by pebbe** [comment]
I would like to search for pages where an image is used if I click on that image.

**Comment by lucaorio** [comment]
Hey everyone, I just added a lightbox feature for the gallery: on the top right of the overlay there's a button that'll open the original image in a new tab.

![CleanShot 2022-12-23 at 00 46 09@2x](https://user-images.githubusercontent.com/299621/209278842-d46d7967-c148-4dad-8e2f-8f8253c7c8ac.jpg)

Once you have the original image opened in a new tab:
@NB574 right-clicking on the tab will let you select the native _Reveal in Finder_.
@pebbe opening the _Backlinks_ panel will show you where that image is being used.

**Comment by pebbe** [comment]
Nice!
