### ISSUE TITLE
FR image captions 

### ISSUE THREAD

**Issue by johans3** [lucaorio/obsidian-image-gallery#6]
Very convenient plugin
Since snippets provide similar results,  i would add some more features, good looking image captures for this container both in LP  and reading mode, like : configurable photo metadata strings and /or custom strings

Also a slideshow for each container would be nice but that's yet another feature request and I'm not sure if that's doable

**Comment by lucaorio** [comment]
Hi @johans3, I just added a slideshow feature to the plugin!

Regarding your first note: this plugin grabs everything is in a folder, so I don't know where one could specify a caption/description for the images. If you really need those, it seems like https://github.com/tokenshift/obsidian-page-gallery might solve your needs!
