### ISSUE TITLE
[FR] readme not showing on Obsidian community plugin page

### ISSUE THREAD

**Issue by andrewcrook** [lucaorio/obsidian-image-gallery#7]
`This plugin did not provide a README file.`

I wonder if Obsidian is case sensitive?
Rename to ` README.txt` ?

**Comment by lucaorio** [comment]
Hi @andrewcrook, thanks for the heads-up. I have been very busy and got to see this just now.

It seems the readme has to be uppercase, or it won't work... I just shipped a fix for it!
